# Generated by Django 5.2.12 on 2026-03-17 07:36

from django.db import migrations


def link_flats_and_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(owner=flat.owner)
        owner.flats.add(flat)


def reverse_link(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_transfer_owners'),
    ]

    operations = [
        migrations.RunPython(link_flats_and_owners, reverse_link),
    ]
