# Generated by Django 5.2.12 on 2026-03-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_link_flats_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
