# Generated by Django 5.2.12 on 2026-03-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_complaint_complainer_alter_complaint_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
    ]
