# Generated by Django 5.2.12 on 2026-03-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_rename_owner_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
